version: '3.6'
services:
  app-tests:
    build:
      context: .
      dockerfile: Dockerfile.testing
    container_name: preferred-api-app-tests
    ports:
    - 80:8080
    environment:
    - DOCUMENT_ROOT=/app/public
    - SKIP_LOCKDOWN_DOCUMENT_ROOT=true
    - OPCACHE_SAVE_COMMENTS=1
    - OPCACHE_VALIDATE_TIMESTAMPS=1
    volumes:
    - .:/app
    depends_on:
    - pgsql-tests
    - redis-tests

  pgsql-tests:
    image: launcher.gcr.io/google/postgresql11
    container_name: preferred-api-pgsql-tests
    ports:
    - 5434:5432
    environment:
      POSTGRES_DB: preferred_tests
      POSTGRES_USER: preferred_tests
      POSTGRES_PASSWORD: preferred_tests
    volumes:
    - preferred-pgsql-tests:/var/lib/postgresql/data

  redis-tests:
    image: launcher.gcr.io/google/redis4
    container_name: preferred-api-redis-tests
    volumes:
    - preferred-redis-tests:/data
    ports:
    - 6378:6379

networks:
  default:
    name: preferred-api_default
volumes:
  preferred-pgsql-tests:
    driver: local
  preferred-redis-tests:
    driver: local
