version: '3.6'
services:
  app:
    build:
      context: .
    container_name: preferred-api-app
    ports:
    - 80:8080
    environment:
    - DOCUMENT_ROOT=/app/public
    - SKIP_LOCKDOWN_DOCUMENT_ROOT=true
    - OPCACHE_SAVE_COMMENTS=1
    - OPCACHE_VALIDATE_TIMESTAMPS=1
    volumes:
    - .:/app
    depends_on:
    - pgsql
    - redis

  pgsql:
    image: launcher.gcr.io/google/postgresql11
    container_name: preferred-api-pgsql
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: preferred
      POSTGRES_USER: preferred
      POSTGRES_PASSWORD: preferred
    volumes:
    - preferred-pgsql:/var/lib/postgresql/data

  redis:
    image: launcher.gcr.io/google/redis4
    container_name: preferred-api-redis
    volumes:
    - preferred-redis:/data
    ports:
    - 6379:6379

networks:
  default:
    name: preferred-api_default
volumes:
  preferred-pgsql:
    driver: local
  preferred-redis:
    driver: local
