name: Commitlint

on: [push]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: wagoid/commitlint-github-action@v1.3.2
      with:
        configFile: './.commitlintrc.yml'

    # - uses: yanzay/notify-telegram@v0.1.0
    #   if: failure()
    #   with:
    #     chat: ${{ secrets.chat }}
    #     token: ${{ secrets.token }}
    #     status: ${{ job.status }}